DIRECTORY:
  dataset: path_to_train.json

AUGMENTATION:
  
TRAINER :
  debug: False
  tokenizer: ElectraTokenizerFast
  model: electra
  pretrained: monologg/koelectra-small-v3-discriminator
  optimizer: adamw
  learning_rate: 5.0e-4
  loss: crossentropy
  metric:
    - accuracy
  n_epochs: 20
  early_stopping_target: val_loss
  early_stopping_patience: 10
  early_stopping_mode: min
  amp: False
  gpu: 0
  seed: 42

MODEL:
  electra:

DATALOADER:
  batch_size: 16
  num_workers: 0
  shuffle: True
  pin_memory: True
  drop_last: False

LOGGER:
  wandb: False
  logging_interval: 200
  plot:
    - loss
    - accuracy