DIRECTORY:
  dataset: dataset

AUGMENTATION:
  random_masking: True
  question_shuffle_aug: True
  pororo_aug: True
  gpt_aug: False
  
TRAINER :
  debug: False
  tokenizer: AutoTokenizer
  model: SDS # AutoModelForQuestionAnswering # Conv # QAConv #SDS #QASDS
  pretrained: klue/roberta-base # klue/roberta-base #large  #xlm-roberta-large #tau/splinter-base
  optimizer: adamw
  learning_rate: 1.0e-6
  loss: crossentropy
  metric:
    - accuracy
  n_epochs: 50
  early_stopping_target: val_loss
  early_stopping_patience: 3
  early_stopping_mode: min
  amp: False
  gpu: 0
  seed: 42
  grad_accum: 8

DATALOADER:
  batch_size: 8
  num_workers: 0
  shuffle: True
  pin_memory: True
  drop_last: False

LOGGER:
  wandb:
    use: True
    username: team-ikyo
    project_serial: aichallenge_2022
  logging_interval: 200
  plot:
    - loss
    - accuracy