DIRECTORY:
  dataset: /aichall_2022_mrc/dataset

AUGMENTATION:
  
TRAINER :
  debug: False
  tokenizer: AutoTokenizer
  model: QAConv # AutoModelForQuestionAnswering # Conv # QAConv
  pretrained: klue/roberta-base # klue/roberta-base #xlm-roberta-large
  optimizer: adamw
  learning_rate: 1.0e-6
  loss: crossentropy
  metric:
    - accuracy
  n_epochs: 20
  early_stopping_target: val_loss
  early_stopping_patience: 3
  early_stopping_mode: min
  amp: False
  gpu: 0
  seed: 42
  grad_accum: 8
  aug: True

DATALOADER:
  batch_size: 8
  num_workers: 0
  shuffle: True
  pin_memory: True
  drop_last: False

LOGGER:
  wandb:
    use: True
    username: team-ikyo
    project_serial: aichallenge_2022
  logging_interval: 200
  plot:
    - loss
    - accuracy